version: '3.8'

services:
  mcp-core-daemon:
    build: .
    container_name: mcp-server
    env_file:
      - .env
    stdin_open: true  # Keep STDIN open for MCP stdio communication
    tty: true         # Allocate a pseudo-TTY
    ports:
      - "${CONTAINER_PORT}:${PORT}"   # Expose port for SSE transport
    volumes:
      - ./logs:/var/log/supervisor
      - ./data:/app/data  # Mount for persistent data if needed
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_ENV=production
      - REGION_NAME=${REGION_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PORT=${PORT}
      - MCP_CONFIG_FILE=${MCP_CONFIG_FILE}
      - AUTH_PROVIDER=${AUTH_PROVIDER}
      - LOCAL_USER_FILE=${LOCAL_USER_FILE}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_STATIC_TOKEN=${ADMIN_STATIC_TOKEN}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
      - COGNITO_APP_SECRET=${COGNITO_APP_SECRET}
      - COGNITO_JWKS_URL=${COGNITO_JWKS_URL}
      - FUNCT_BUCKET_NAME=${FUNCT_BUCKET_NAME}
      - FUNCT_ZIP_PATH=${FUNCT_ZIP_PATH}
      - FUNCT_EXTRACT_PATH=${FUNCT_EXTRACT_PATH}
    restart: no # unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health", "||", "echo", "stdio mode"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]  # Start supervisor as root (it will drop privileges for child processes)